### ISSUE TITLE
does not work with PHP 7.2

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/limit_login_to_ip#12]
would be nice to update it before 13...

**Comment by digilur** [comment]
+1 - Upgraded to Nextcloud 12.5 -> 13.0.0, PHP 5.6 -> 7.2 and lost this feature, would love it back.

**Comment by MorrisJobke** [comment]
Fixed by #15

**Comment by MorrisJobke** [comment]
Released in the appstore as 1.0.3
