### ISSUE TITLE
NC 15/16/17/18 Compatibility

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/limit_login_to_ip#23]
Sorry for bothering, but is there a release date for Nextcloud 15 compatibility? I would really like to update to NC 15, but I need this helpful app, too.

**Comment by Elfanar** [comment]
Its very helpful to use it on NC 15, any release date ?

**Comment by LeoTuk** [comment]
I too would like to use this with NC 15.

**Comment by 321freddy** [comment]
I could get version 1.0.4 to work with NC 15 just by changing one line in the `appinfo/info.xml` from
`<nextcloud min-version="13" max-version="14" />`
to
`<nextcloud min-version="13" max-version="15" />`

**Comment by ducemollari** [comment]
Me to waiting for NC15 compatible release.

**Comment by Desdemo** [comment]
me too

**Comment by Peter1495** [comment]
Yes, when will NC15 be compatible?? And @321freddy is it working properly? Tested with version 2.0? I really need this in my 'no-domain setup'. This is a really nice plugin for home/local users to add more security.

**Comment by 321freddy** [comment]
@Peter1495 Version 1.0.4 with the fix works great in NC15.

But I think version 2.0 is already NC15/16 compatible, just not yet available on the app store. See #27

**Comment by Peter1495** [comment]
Nice, how can I install it without the app store? Can't find a guide online in a quick search, I'm new to Nextcloud.

**Comment by 321freddy** [comment]
Download the repo as ZIP, unpack it on your server in `/var/www/html/custom_apps/limit_login_to_ip` and finally activate it in Nextcloud app list as usual

**Comment by Peter1495** [comment]
Thanks (also for the fast reply), will try it tomorrow :)

**Comment by yetiinabox** [comment]
Apologies if I'm being terribly stupid, but I have downloaded v 2.0.0 into a separate app directory, configured in config.php — and the app does show up (as v.2.0.0) in the app list. Rather than 'enable', it has an option to "Download and enable" (which fails, complaining about version incompatibility). It's somehow not completely recognizing the code that has been downloaded. What am I missing?

**Comment by yetiinabox** [comment]
Answering my own question: the unzipped file had the directory name limit_login_to_ip-master and of course, exactly as you said above, it had to have the name limit_login_to_ip . Sigh. Thanks.

**Comment by ducemollari** [comment]
Is it possible at all to make the app compatible with NC15/16?
I'd tested it in manual install, all works, but I need to instal it from apps menu. Now I can do it, but there is warning about untested app. Not my way, I have to use Official apps and with no warning signs (such organization's policies).

**Comment by skjnldsv** [comment]
Fixed by https://github.com/nextcloud/limit_login_to_ip/pull/32

**Comment by skjnldsv** [comment]
Let's release a new one.
Please note that since nc 17, you can enable apps that are not declared as compatible with your current newer version :)

**Comment by reiner-text** [comment]
>  Please note that since nc 17, you can enable apps that are not declared as compatible with your current newer version :)

However, this does not prevent a lack of publication in the app store from flagging this app as incompatible within the Nextcloud instance. Not everyone wants to allow every single app this way. Is it really that hard to post an update in the app store when the app has already been updated on GitHub?

**Comment by skjnldsv** [comment]
> Is it really that hard to post an update in the app store when the app has already been updated on GitHub?

Depends on the way you phrase your requests or not?
This is not how I'm used to collaborate and it will most likely not give anyone the will to help you.
Please reconsider your phrasing and incentives :)
Thanks! :v:

**Comment by reiner-text** [comment]
@skjnldsv Neither I’m a native English speaker, nor do I use English in everyday life. If you’re pissed off about my wording, ignore me if my inadequate language skills cause you such problems!
