### ISSUE TITLE
make 18 compatible

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/limit_login_to_ip#31]
This is a featured app, but not yet made 18-ready. Please don't let that get forgotten.

Also, the app store needs to be supplied with the latest releases:

![image](https://user-images.githubusercontent.com/1804221/71824275-74725180-3099-11ea-8730-c30e18e61211.png)

@rullzer

**Comment by wiswedel** [comment]
Also, since NC 18 will support PHP 7.4, you might wanna consider applying that also to this app once releasing it for 18.

**Comment by rullzer** [comment]
Is this featured? Would make sense to drop that. This is a weird app anyways

**Comment by wiswedel** [comment]
![image](https://user-images.githubusercontent.com/1804221/71828003-c7500700-30a1-11ea-9bd4-65b184ec84bc.png)

**Comment by skjnldsv** [comment]
Lots of customer uses it though :(
I find it a nice simple app to be honest ;)

**Comment by skjnldsv** [comment]
see #23
