### ISSUE TITLE
Upload CSV-Files for resticting many IP-ranges

### ISSUE THREAD

**Issue by erikbarz** [nextcloud/limit_login_to_ip#48]
Hi,

I would really like to block IP addresses from foreign countries. It would be a cool feature to have a bulk upload here to restrict or allow loads of IP ranges. 

For example I can downloadall German IP ranges here:
https://lite.ip2location.com/germany-ip-address-ranges

An CSV-upload would allow me to only allow (Whitelist) these IPs

Thank you in advance!
Erik

**Comment by Altahrim** [comment]
You probably already found a solution, but maybe you should look at [Geoblocker app](https://apps.nextcloud.com/apps/geoblocker)
It seems to do exactly what you want :)
