### ISSUE TITLE
ArithmeticError

### ISSUE THREAD

**Issue by pulsarfish** [nextcloud/limit_login_to_ip#55]
App will not enable, logs show **ArithmeticError: Bit shift by negative number.**

{"reqId":"VgVM1flUhQNbqc04mcnY","level":3,"time":"2020-11 26T05:40:16+00:00","remoteAddr":"<ip addr>","user":"<usermane>","app":"no app in context","method":"GET","url":"/index.php/apps/files","message":{"Exception":"ArithmeticError","Message":"Bit shift by negative number","Code":0,"Trace":[{"file":"/var/www/html/apps/limit_login_to_ip/lib/LoginHookListener.php","line":84,"function":"matchCidr","class":"OCA\\LimitLoginToIp\\LoginHookListener","type":"->"},{"file":"/var/www/html/apps/limit_login_to_ip/appinfo/app.php","line":40,"function":"isLoginAllowed","class":"OCA\\LimitLoginToIp\\LoginHookListener","type":"->"},{"file":"/var/www/html/lib/private/legacy/app.php","line":266,"args":["/var/www/html/apps/limit_login_to_ip/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/html/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::"},{"file":"/var/www/html/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::"},{"file":"/var/www/html/lib/base.php","line":993,"function":"loadApps","class":"OC_App","type":"::"},{"file":"/var/www/html/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/html/apps/limit_login_to_ip/lib/LoginHookListener.php","Line":67,"CustomMessage":"--"}

**Comment by Altahrim** [comment]
I think this one is outdated. Feel free to reopen if needed :)
