### ISSUE TITLE
Restrict login to IP addresses s getting diabled

### ISSUE THREAD

**Issue by ihsystems** [nextcloud/limit_login_to_ip#58]
When I added this it worked fine for couple of days and today it disappeared from "My Apps" and when I am trying to enable it, it enables it but when I go to security it does not exists - go back to Apps menu and it shows "Disable"

**Comment by ihsystems** [comment]
O/S: Centos 7, Upgraded to 19 from 18 but still same behavior - 
a. Showing in Disabled Apps list Click Enabled (some times as for Admin password & other times not)
b. Showing in Active App
c. Go to Admin -> Setting oops not available
d. Cycle from a - c again & again but same issue 
Though couple of times it appeared but gone/disappear after little while.

Any suggestion ?

**Comment by ihsystems** [comment]
After further trouble shooting I noticed its getting disabled if I add IPv6 it works if I have only IPv4 IP addresses assigned.

**Comment by ihsystems** [comment]
If by jistake add an IPv6 address boom it just disappear and never able to enable it again - BIG BUG

**Comment by Altahrim** [comment]
IPv6 are now supported
