### ISSUE TITLE
Please add compatibility with Nextcloud V23

### ISSUE THREAD

**Issue by leonardohlee** [nextcloud/limit_login_to_ip#67]
Please add compatibility with Nextcloud V23

**Comment by bluesky-ca** [comment]
And now V24 - IP blocking and 2FA with IP ie being able to limit 2FA to external subnets.  The 2FA IP has been proposed in 2016 on github and test code in 2021 - hope this makes it in at some point [(link).](https://github.com/nextcloud/server/issues/2035)  Any good security includes layers of protection

**Comment by Altahrim** [comment]
Hello, 
We just released a new beta version for Nextcloud v26+ :) 
Versions v22 to v25 were skipped.
