### ISSUE TITLE
Feature request: Restrict TOTP/2FA to IP-range

### ISSUE THREAD

**Issue by TomTeeJay** [nextcloud/limit_login_to_ip#7]
In our company we use smartphones with freeOTP App for TOTP Auth in Nextcloud though it would be great to whitelist internal segment in order to give employees without smartphones access to nextcloud. Or perhaps to disable TOTP/2FA from internal and enable it when loggin in from external IPs?

**Comment by mario** [comment]
Don't think this is what we'd want to do, but that's just me. 2FA is important, even internally since you can either have compromised machines, saved passwords or various other things.

cc @rullzer and @MorrisJobke to help decide on this :)

**Comment by rullzer** [comment]
2FA is important. And we don't allow apps to disable it.

What you could do is write a dummy 2FA app that always passes when you are on the right subnet. But that is out of scope for this app
