### ISSUE TITLE
Please maintain the app

### ISSUE THREAD

**Issue by isotipu** [nextcloud/limit_login_to_ip#73]
Hi, we're living Nextcloud v. 25 now and I wonder whether you're going to update the app so that it can be used in the actual versions of Nextcloud. 
The Idea of limiting access to the nextcloud instance hits a nerve, especially for oganisations, where it has to be secured that outside access is impossible or only able for privileged users. 
I appreaciate your work very much.

**Comment by Altahrim** [comment]
Hello, 
We just released a new beta version for Nextcloud v26+ :)
