### ISSUE TITLE
limit_login_to_ip app not working

### ISSUE THREAD

**Issue by CamZie** [nextcloud/limit_login_to_ip#8]
Hello,

I have downloaded and enabled this app for my Nextcloud installation and ran the command to set the IP addresses that I wanted to be whitelisted, as mentioned in the apps documentation. After that, I tried to access my installation using another IP, which is not whitelisted, but unfortunately it is still accessible. Any clues as to why this could be?

**Comment by jospoortvliet** [comment]
Anything in the logs?

**Comment by CamZie** [comment]
Unfortunately there was nothing in the logs.

**Comment by lalalolo49** [comment]
Encounter the same issue
_2018/02/25_ 01:49:29 [error] 627#627: *XX access forbidden by rule, client: xx.xx.xx.xx, server: myserver.my, request: "GET /data/.ocdata?t=1519519770308  HTTP/1.1", host: "myserver.my"_

But still get access to nextcloud login and can login

**Comment by rullzer** [comment]
Can you post the output of the query:

```sql
SELECT *
FROM oc_appconfig 
WHERE appid='limit_login_to_ip'
```

**Comment by lalalolo49** [comment]
+-------------------+--------------------+-----------------+
 | appid                | configkey                 | configvalue     |
+----------------+--------------------+--------------+
 | limit_login_to_ip | enabled                   | yes                 |
 | limit_login_to_ip | installed_version      | 1.0.3               |
 | limit_login_to_ip | types                       | filesystem       |
 | limit_login_to_ip | whitelisted.ranges    | ,xx.xx.xx.xx/      |
+----------------+---------------------+--------------+

**I have whitelisted my house IP**
**I used my 4G to connect to it and it still connect**

**Comment by rullzer** [comment]
Ah well yes your range is invalid.

Let me try to push a fix that should catch it.
